### ISSUE TITLE
Error when frontmatter value contains colon

### ISSUE THREAD

**Issue by qifei9** [beaussan/update-time-on-edit-obsidian#17]
When the original frontmatter is

```yaml
---
key: "a:b"
---
```

After addition of timestamp by the plugin, it will become

```yaml
---
key: "a:
created: 2021-11-30, 17:55
updated: 2021-11-30, 17:55
---
```
