### ISSUE TITLE
Rewrites blank frontmatter to be null

### ISSUE THREAD

**Issue by doug-w** [beaussan/update-time-on-edit-obsidian#52]
I have a contact template that has fields like:

```
---
company:
location:
title:
email:
---
```

After editing a contact with this plugin enabled it becomes
```
---
company: null
location: null
title: null
email: null
updated: 2023-07-29T11:31
created: 2023-05-28T09:28
---
```

I expect only the created and updated fields to be changed and not every field that was blank

**Comment by Buddinski88** [comment]
Thank you for opening that Bug, because i have the same issue with version 2.0.1 and also 2.0.2.

I have this set of frontmatter yaml:
```yaml
---
tags: 🧠️/📝️/🌱️
type: "doc"
active: perhaps
publish: false
aliases: 
created: 2023-07-25 11:40
updated: 2023-07-29 20:06
---
```

When i for example change `type: "doc"` to `type: doc` then the frontmatterdata locks like this:
```yaml
---
tags: 🧠️/📝️/🌱️
type: doc
active: perhaps
publish: false
aliases: null
created: 2023-07-25 11:40
updated: 2023-07-29 20:06
---
```

Deleting the `null` from "aliases" and add the quotationmarks like in the first example, then everything will be changed back as in the second example.

After i disable the plugin everything works fine.
